// <auto-generated />
using System;
using CinemaBookingApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaBookingApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Actor", b =>
                {
                    b.Property<long>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ActorId"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ActorId");

                    b.ToTable("Actor");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Cinema", b =>
                {
                    b.Property<long>("CinemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CinemaId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Hotline")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CinemaId");

                    b.ToTable("Cinema");

                    b.HasData(
                        new
                        {
                            CinemaId = 1L,
                            Address = "30 Bờ Bao Tân Thắng, P. Sơn Kỳ, Q. Tân Phú, TP. HCM",
                            City = "TP. HCM",
                            Hotline = "19001234",
                            Name = "CGV Aeon Tân Phú"
                        },
                        new
                        {
                            CinemaId = 2L,
                            Address = "72 Lê Thánh Tôn, P. Bến Nghé, Q. 1, TP. HCM",
                            City = "TP. HCM",
                            Hotline = "19001234",
                            Name = "CGV Vincom Đồng Khởi"
                        },
                        new
                        {
                            CinemaId = 3L,
                            Address = "240-242 Phạm Văn Đồng, Thủ Đức, TP. HCM",
                            City = "TP. HCM",
                            Hotline = "19001234",
                            Name = "CGV Giga Mall"
                        },
                        new
                        {
                            CinemaId = 4L,
                            Address = "1 Đại lộ Bình Dương, Thuận An, Bình Dương",
                            City = "Bình Dương",
                            Hotline = "19001234",
                            Name = "CGV Aeon Bình Dương Canary"
                        },
                        new
                        {
                            CinemaId = 5L,
                            Address = "101 Tôn Dật Tiên, P. Tân Phú, Q.7, TP. HCM",
                            City = "TP. HCM",
                            Hotline = "19001234",
                            Name = "CGV Crescent Mall"
                        },
                        new
                        {
                            CinemaId = 6L,
                            Address = "191 Bà Triệu, Hai Bà Trưng, Hà Nội",
                            City = "Hà Nội",
                            Hotline = "19001234",
                            Name = "CGV Vincom Bà Triệu"
                        },
                        new
                        {
                            CinemaId = 7L,
                            Address = "458 Minh Khai, Hai Bà Trưng, Hà Nội",
                            City = "Hà Nội",
                            Hotline = "19001234",
                            Name = "CGV Times City"
                        },
                        new
                        {
                            CinemaId = 8L,
                            Address = "910A Ngô Quyền, Sơn Trà, Đà Nẵng",
                            City = "Đà Nẵng",
                            Hotline = "19001234",
                            Name = "CGV Vincom Đà Nẵng"
                        },
                        new
                        {
                            CinemaId = 9L,
                            Address = "Đường Cầu Bươu, P. Kiến Hưng, Hà Đông, Hà Nội",
                            City = "Hà Nội",
                            Hotline = "19001234",
                            Name = "CGV Aeon Hà Đông"
                        },
                        new
                        {
                            CinemaId = 10L,
                            Address = "72A Nguyễn Trãi, Thanh Xuân, Hà Nội",
                            City = "Hà Nội",
                            Hotline = "19001234",
                            Name = "CGV Vincom Mega Mall Royal City"
                        },
                        new
                        {
                            CinemaId = 11L,
                            Address = "126 Hồng Bàng, Q.5, TP. HCM",
                            City = "TP. HCM",
                            Hotline = "19001234",
                            Name = "CGV Parkson Hùng Vương"
                        },
                        new
                        {
                            CinemaId = 12L,
                            Address = "Tầng 6, 54A Nguyễn Chí Thanh, Hà Nội",
                            City = "Hà Nội",
                            Hotline = "19001234",
                            Name = "CGV Nguyễn Chí Thanh"
                        },
                        new
                        {
                            CinemaId = 13L,
                            Address = "1058 Nguyễn Văn Linh, Q.7, TP. HCM",
                            City = "TP. HCM",
                            Hotline = "19001234",
                            Name = "CGV SC VivoCity"
                        },
                        new
                        {
                            CinemaId = 14L,
                            Address = "54A Nguyễn Chí Thanh, Đống Đa, Hà Nội",
                            City = "Hà Nội",
                            Hotline = "19001234",
                            Name = "CGV Vincom Nguyễn Chí Thanh"
                        },
                        new
                        {
                            CinemaId = 15L,
                            Address = "Khu phố Đông Tân, P. Dĩ An, TP. Dĩ An, Bình Dương",
                            City = "Bình Dương",
                            Hotline = "19001234",
                            Name = "CGV Big C Dĩ An"
                        },
                        new
                        {
                            CinemaId = 16L,
                            Address = "126 Hùng Vương, Q.5, TP. HCM",
                            City = "TP. HCM",
                            Hotline = "19001234",
                            Name = "CGV Hùng Vương Plaza"
                        });
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Client", b =>
                {
                    b.Property<long>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Genre")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<double>("LoyalPoints")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("RankId")
                        .HasColumnType("bigint");

                    b.HasKey("ClientId");

                    b.HasIndex("RankId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Combo", b =>
                {
                    b.Property<long>("ComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ComboId"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ComboId");

                    b.ToTable("Combo");

                    b.HasData(
                        new
                        {
                            ComboId = 1L,
                            ImageURL = "/images/combos/combo1.jpg",
                            Name = "Combo 1: Bắp + Nước",
                            Price = 65m,
                            Quantity = 100,
                            Status = true
                        },
                        new
                        {
                            ComboId = 2L,
                            ImageURL = "/images/combos/combo2.jpg",
                            Name = "Combo 2: 2 Bắp + 2 Nước",
                            Price = 120m,
                            Quantity = 80,
                            Status = true
                        },
                        new
                        {
                            ComboId = 3L,
                            ImageURL = "/images/combos/combo_family.jpg",
                            Name = "Combo Gia đình: 2 Bắp lớn + 3 Nước",
                            Price = 160m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            ComboId = 4L,
                            ImageURL = "/images/combos/combo_chicken.jpg",
                            Name = "Combo Gà Rán + Nước",
                            Price = 90m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            ComboId = 5L,
                            ImageURL = "/images/combos/combo_birthday.jpg",
                            Name = "Combo Sinh Nhật Đặc Biệt",
                            Price = 150m,
                            Quantity = 20,
                            Status = true
                        },
                        new
                        {
                            ComboId = 6L,
                            ImageURL = "/images/combos/combo_kid.jpg",
                            Name = "Combo Trẻ Em: Bắp nhỏ + Nước cam",
                            Price = 55m,
                            Quantity = 40,
                            Status = true
                        },
                        new
                        {
                            ComboId = 7L,
                            ImageURL = "/images/combos/combo_couple.jpg",
                            Name = "Combo Couple: 1 Bắp lớn + 2 Nước",
                            Price = 110m,
                            Quantity = 60,
                            Status = true
                        },
                        new
                        {
                            ComboId = 8L,
                            ImageURL = "/images/combos/combo_save.jpg",
                            Name = "Combo Tiết Kiệm: Bắp vừa + Nước ngọt",
                            Price = 65m,
                            Quantity = 100,
                            Status = true
                        },
                        new
                        {
                            ComboId = 9L,
                            ImageURL = "/images/combos/combo_nuggets.jpg",
                            Name = "Combo Gà Nuggets + Pepsi",
                            Price = 85m,
                            Quantity = 30,
                            Status = true
                        },
                        new
                        {
                            ComboId = 10L,
                            ImageURL = "/images/combos/combo_cheese.jpg",
                            Name = "Combo Phô Mai: Bắp phô mai + 7Up",
                            Price = 70m,
                            Quantity = 25,
                            Status = true
                        },
                        new
                        {
                            ComboId = 11L,
                            ImageURL = "/images/combos/combo_bbq.jpg",
                            Name = "Combo BBQ: Bắp vị BBQ + Coca",
                            Price = 70m,
                            Quantity = 45,
                            Status = true
                        },
                        new
                        {
                            ComboId = 12L,
                            ImageURL = "/images/combos/combo_vip.jpg",
                            Name = "Combo VIP: 2 Bắp + 2 Nước + Snack",
                            Price = 135m,
                            Quantity = 15,
                            Status = true
                        },
                        new
                        {
                            ComboId = 13L,
                            ImageURL = "/images/combos/combo_valentine.jpg",
                            Name = "Combo Valentine: Bắp tim + Trà Đào",
                            Price = 95m,
                            Quantity = 70,
                            Status = true
                        },
                        new
                        {
                            ComboId = 14L,
                            ImageURL = "/images/combos/combo_student.jpg",
                            Name = "Combo Sinh viên: Bắp + Pepsi nhỏ",
                            Price = 50m,
                            Quantity = 75,
                            Status = true
                        },
                        new
                        {
                            ComboId = 15L,
                            ImageURL = "/images/combos/combo_vegan.jpg",
                            Name = "Combo Chay: Bắp rang bơ + Nước suối",
                            Price = 60m,
                            Quantity = 20,
                            Status = true
                        });
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.ComboTicket", b =>
                {
                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.Property<long>("ComboId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("TicketId", "ComboId");

                    b.HasIndex("ComboId");

                    b.ToTable("ComboTicket");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Coupon", b =>
                {
                    b.Property<long>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CouponId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CouponId");

                    b.ToTable("Coupon");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.CouponUser", b =>
                {
                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<long>("CouponId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.HasKey("ClientId", "CouponId");

                    b.HasIndex("CouponId");

                    b.ToTable("CouponUser");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Favorite", b =>
                {
                    b.Property<long>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FavoriteId"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<long>("MovieId")
                        .HasColumnType("bigint");

                    b.HasKey("FavoriteId");

                    b.HasIndex("ClientId");

                    b.HasIndex("MovieId");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Genre", b =>
                {
                    b.Property<long>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GenreId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GenreId");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            GenreId = 1L,
                            Name = "Hành động"
                        },
                        new
                        {
                            GenreId = 2L,
                            Name = "Phiêu lưu"
                        },
                        new
                        {
                            GenreId = 3L,
                            Name = "Kinh dị"
                        },
                        new
                        {
                            GenreId = 4L,
                            Name = "Hài"
                        },
                        new
                        {
                            GenreId = 5L,
                            Name = "Tình cảm"
                        },
                        new
                        {
                            GenreId = 6L,
                            Name = "Tâm lý"
                        },
                        new
                        {
                            GenreId = 7L,
                            Name = "Gia đình"
                        },
                        new
                        {
                            GenreId = 8L,
                            Name = "Hoạt hình"
                        },
                        new
                        {
                            GenreId = 9L,
                            Name = "Viễn tưởng"
                        },
                        new
                        {
                            GenreId = 10L,
                            Name = "Khoa học viễn tưởng"
                        },
                        new
                        {
                            GenreId = 11L,
                            Name = "Kỳ ảo"
                        },
                        new
                        {
                            GenreId = 12L,
                            Name = "Tội phạm"
                        },
                        new
                        {
                            GenreId = 13L,
                            Name = "Chiến tranh"
                        },
                        new
                        {
                            GenreId = 14L,
                            Name = "Hình sự"
                        },
                        new
                        {
                            GenreId = 15L,
                            Name = "Lịch sử"
                        },
                        new
                        {
                            GenreId = 16L,
                            Name = "Tài liệu"
                        },
                        new
                        {
                            GenreId = 17L,
                            Name = "Âm nhạc"
                        },
                        new
                        {
                            GenreId = 18L,
                            Name = "Võ thuật"
                        },
                        new
                        {
                            GenreId = 19L,
                            Name = "Thể thao"
                        },
                        new
                        {
                            GenreId = 20L,
                            Name = "Thần thoại"
                        },
                        new
                        {
                            GenreId = 21L,
                            Name = "Chính kịch"
                        },
                        new
                        {
                            GenreId = 22L,
                            Name = "Chính trị"
                        },
                        new
                        {
                            GenreId = 23L,
                            Name = "Thiếu nhi"
                        },
                        new
                        {
                            GenreId = 24L,
                            Name = "Học đường"
                        },
                        new
                        {
                            GenreId = 25L,
                            Name = "Kinh điển"
                        },
                        new
                        {
                            GenreId = 26L,
                            Name = "Giả tưởng hậu tận thế"
                        },
                        new
                        {
                            GenreId = 27L,
                            Name = "Siêu anh hùng"
                        },
                        new
                        {
                            GenreId = 28L,
                            Name = "Kịch tính"
                        },
                        new
                        {
                            GenreId = 29L,
                            Name = "Trinh thám"
                        },
                        new
                        {
                            GenreId = 30L,
                            Name = "Thám hiểm"
                        });
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.GenreMovie", b =>
                {
                    b.Property<long>("MovieId")
                        .HasColumnType("bigint");

                    b.Property<long>("GenreId")
                        .HasColumnType("bigint");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GenreMovie");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Movie", b =>
                {
                    b.Property<long>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MovieId"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PosterURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("RequireAge")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TotalBooking")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalLike")
                        .HasColumnType("bigint");

                    b.Property<string>("TrailerURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MovieId");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.MovieActor", b =>
                {
                    b.Property<long>("MovieId")
                        .HasColumnType("bigint");

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActor");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.PasswordResetCode", b =>
                {
                    b.Property<Guid>("PasswordResetCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PasswordResetCodeId");

                    b.ToTable("PasswordResetCode");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Rank", b =>
                {
                    b.Property<long>("RankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RankId"));

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("RequirePoint")
                        .HasColumnType("float");

                    b.HasKey("RankId");

                    b.ToTable("Rank");

                    b.HasData(
                        new
                        {
                            RankId = 1L,
                            Discount = 0.0,
                            Name = "NONE",
                            RequirePoint = 0.0
                        },
                        new
                        {
                            RankId = 2L,
                            Discount = 2.0,
                            Name = "SILVER",
                            RequirePoint = 2000.0
                        },
                        new
                        {
                            RankId = 3L,
                            Discount = 5.0,
                            Name = "GOLD",
                            RequirePoint = 10000.0
                        },
                        new
                        {
                            RankId = 4L,
                            Discount = 10.0,
                            Name = "PLATINUM",
                            RequirePoint = 30000.0
                        });
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Review", b =>
                {
                    b.Property<long>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReviewId"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("MovieId")
                        .HasColumnType("bigint");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("ClientId");

                    b.HasIndex("MovieId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Room", b =>
                {
                    b.Property<long>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoomId"));

                    b.Property<long>("CinemaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("RoomTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("RoomId");

                    b.HasIndex("CinemaId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.RoomType", b =>
                {
                    b.Property<long>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoomTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalSeat")
                        .HasColumnType("int");

                    b.HasKey("RoomTypeId");

                    b.ToTable("RoomType");

                    b.HasData(
                        new
                        {
                            RoomTypeId = 1L,
                            Name = "Large",
                            TotalSeat = 140
                        },
                        new
                        {
                            RoomTypeId = 2L,
                            Name = "Small",
                            TotalSeat = 70
                        });
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Seat", b =>
                {
                    b.Property<long>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SeatId"));

                    b.Property<int>("Column")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("SeatTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("SeatId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SeatTypeId");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.SeatType", b =>
                {
                    b.Property<long>("SeatTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SeatTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("SeatTypeId");

                    b.ToTable("SeatType");

                    b.HasData(
                        new
                        {
                            SeatTypeId = 1L,
                            Name = "Sweet Box",
                            Price = 125.0
                        },
                        new
                        {
                            SeatTypeId = 2L,
                            Name = "VIP",
                            Price = 105.0
                        },
                        new
                        {
                            SeatTypeId = 3L,
                            Name = "Normal",
                            Price = 100.0
                        },
                        new
                        {
                            SeatTypeId = 4L,
                            Name = "GOLD CLASS",
                            Price = 300.0
                        });
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.ShowingTime", b =>
                {
                    b.Property<long>("ShowingTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ShowingTimeId"));

                    b.Property<long>("MovieId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ShowingTimeId");

                    b.HasIndex("MovieId");

                    b.HasIndex("RoomId");

                    b.ToTable("ShowingTime");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Ticket", b =>
                {
                    b.Property<long>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TicketId"));

                    b.Property<string>("CinemaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CouponId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("LoyalPointsUsed")
                        .HasColumnType("float");

                    b.Property<long>("MovieId")
                        .HasColumnType("bigint");

                    b.Property<long>("ShowingTimeId")
                        .HasColumnType("bigint");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<double>("TotalPriceCombos")
                        .HasColumnType("float");

                    b.Property<double>("TotalPriceDiscount")
                        .HasColumnType("float");

                    b.Property<double>("TotalPriceSeats")
                        .HasColumnType("float");

                    b.Property<double>("TotalRankDiscount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TicketId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CouponId");

                    b.HasIndex("MovieId");

                    b.HasIndex("ShowingTimeId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.TicketSeat", b =>
                {
                    b.Property<long>("SeatId")
                        .HasColumnType("bigint");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.HasKey("SeatId", "TicketId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketSeat");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Client", b =>
                {
                    b.HasOne("CinemaBookingApp.Models.Entities.Rank", "Rank")
                        .WithMany("Clients")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.ComboTicket", b =>
                {
                    b.HasOne("CinemaBookingApp.Models.Entities.Combo", "Combo")
                        .WithMany("ComboTickets")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBookingApp.Models.Entities.Ticket", "Ticket")
                        .WithMany("ComboTickets")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.CouponUser", b =>
                {
                    b.HasOne("CinemaBookingApp.Models.Entities.Client", "Client")
                        .WithMany("CouponUsers")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBookingApp.Models.Entities.Coupon", "Coupon")
                        .WithMany("CouponUsers")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Favorite", b =>
                {
                    b.HasOne("CinemaBookingApp.Models.Entities.Client", "Client")
                        .WithMany("Favorites")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBookingApp.Models.Entities.Movie", "Movie")
                        .WithMany("Favorites")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.GenreMovie", b =>
                {
                    b.HasOne("CinemaBookingApp.Models.Entities.Genre", "Genre")
                        .WithMany("GenreMovies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBookingApp.Models.Entities.Movie", "Movie")
                        .WithMany("GenreMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.MovieActor", b =>
                {
                    b.HasOne("CinemaBookingApp.Models.Entities.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBookingApp.Models.Entities.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Review", b =>
                {
                    b.HasOne("CinemaBookingApp.Models.Entities.Client", "Client")
                        .WithMany("Reviews")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBookingApp.Models.Entities.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Room", b =>
                {
                    b.HasOne("CinemaBookingApp.Models.Entities.Cinema", "Cinema")
                        .WithMany("Rooms")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBookingApp.Models.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Seat", b =>
                {
                    b.HasOne("CinemaBookingApp.Models.Entities.Room", "Room")
                        .WithMany("Seats")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBookingApp.Models.Entities.SeatType", "SeatType")
                        .WithMany("Seats")
                        .HasForeignKey("SeatTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("SeatType");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.ShowingTime", b =>
                {
                    b.HasOne("CinemaBookingApp.Models.Entities.Movie", "Movie")
                        .WithMany("ShowingTimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBookingApp.Models.Entities.Room", "Room")
                        .WithMany("ShowingTimes")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Ticket", b =>
                {
                    b.HasOne("CinemaBookingApp.Models.Entities.Client", "Client")
                        .WithMany("Tickets")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBookingApp.Models.Entities.Coupon", "Coupon")
                        .WithMany("Tickets")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CinemaBookingApp.Models.Entities.Movie", "Movie")
                        .WithMany("Tickets")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBookingApp.Models.Entities.ShowingTime", "ShowingTime")
                        .WithMany("Tickets")
                        .HasForeignKey("ShowingTimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Coupon");

                    b.Navigation("Movie");

                    b.Navigation("ShowingTime");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.TicketSeat", b =>
                {
                    b.HasOne("CinemaBookingApp.Models.Entities.Seat", "Seat")
                        .WithMany("TicketSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBookingApp.Models.Entities.Ticket", "Ticket")
                        .WithMany("TicketSeats")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Cinema", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Client", b =>
                {
                    b.Navigation("CouponUsers");

                    b.Navigation("Favorites");

                    b.Navigation("Reviews");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Combo", b =>
                {
                    b.Navigation("ComboTickets");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Coupon", b =>
                {
                    b.Navigation("CouponUsers");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Genre", b =>
                {
                    b.Navigation("GenreMovies");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Movie", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("GenreMovies");

                    b.Navigation("MovieActors");

                    b.Navigation("Reviews");

                    b.Navigation("ShowingTimes");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Rank", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Room", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("ShowingTimes");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Seat", b =>
                {
                    b.Navigation("TicketSeats");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.SeatType", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.ShowingTime", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CinemaBookingApp.Models.Entities.Ticket", b =>
                {
                    b.Navigation("ComboTickets");

                    b.Navigation("TicketSeats");
                });
#pragma warning restore 612, 618
        }
    }
}
